# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
 boot.extraModprobeConfig = ''
    options snd slots=snd_hda_intel,snd_usb_audio

    options snd_hda_intel index=0 model=alc1220

    options snd_usb_audio index=1
  '';
    sound.extraConfig = ''
    defaults.pcm.card 0
    defaults.ctl.card 0
  '';
boot.kernelPackages = pkgs.linuxPackages_latest;
boot.blacklistedKernelModules = [ "snd_hda_codec_hdmi" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e4282938-ba80-4f5f-b18c-be10a01e6e45";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
